- name: Install websever on Terraform created EC2 instance
  remote_user: ec2-user
  hosts: all
  become: true

  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: ansiadmin
      state: present
      key: "{{ lookup('file', '/home/admin/.ssh/id_rsa.pub') }}"
